# Jobs
# ---------
jobs:

# Job - Audit Dependencies
# ---------
- job: Audit
  displayName: Audit Dependencies
  steps:
  - script: npm audit --audit-level=moderate
    displayName: Audit (Dev)
    continueOnError: true

  - script: npm audit --production --audit-level=high
    displayName: Audit (Prod)
